pipeline {
    agent any

    stages {
        stage("Build") {
            agent {
                docker {
                    image "node:18-alpine"
                    reuseNode true
                }
            }
            steps {
                sh '''
                ls -la
                node --version
                npm --version
                npm ci
                npm run build
                ls -la
                '''
            }
        }
        // stage('w/o Docker') {
        //     steps {
        //         sh "echo 'Without Docker'"
        //     }
        // }
        
        // stage('w/ Docker') {
        //     agent {
        //         docker {
        //             image "node:18-alpine"
        //             reuseNode true
        //         }
        //     }
        //     steps {
        //         sh "echo 'With Docker'"
        //     }
        // }
    }
}
