pipeline {
    agent any

    stages {
        stage("Hello") {
            steps {
                sh 'echo "Hello World"'
            }
        }
        // stage('w/o Docker') {
        //     steps {
        //         sh "echo 'Without Docker'"
        //     }
        // }
        
        // stage('w/ Docker') {
        //     agent {
        //         docker {
        //             image "node:18-alpine"
        //             reuseNode true
        //         }
        //     }
        //     steps {
        //         sh "echo 'With Docker'"
        //     }
        // }
    }
}
